next_books = [
	{"auteur": "Hume", "titre": "Enquête sur l entendement humain"},
	{"auteur": "Maupassant", "titre":"Le Horla"},
	{"auteur": "La Boétie", "titre":"Discours sur la servitude volontaire"},
	{"auteur": "Paul Carrell", "titre":"Opération Barbarossa"},
	{"auteur": "Giulio Bedeschi", "titre":"Cent mille gamelles de glace"},
	{"auteur": "Grigori Baklanov", "titre":"Juillet 41"},
	{"auteur": "Jules Verne", "titre":"Voyages et aventures du capitaine Hatteras"},
	{"auteur": "Arthur Conan Doyle", "titre":"Son dernier coup d archet"},
	{"auteur": "Dostoievski", "titre":"Crime et châtiment"},
	{"auteur": "Ernest Cline", "titre":"Ready Player One"},
	{"auteur": "Umberto Eco", "titre":"Le nom de la rose",},
	{"auteur": "Nabokov", "titre":"Lolita",},
	{"auteur": "Dickens", "titre":"David Copperfield"},
	{"auteur": "Gregory Bateson", "titre":"Vers une écologie de l esprit"},
	{"auteur": "Edward Abbey", "titre":"Gang de la clef à molette"},
	{"auteur": "Henry David Thoreau", "titre":"La désobéissance civile"},
	{"auteur": "Edward Bernay", "titre":"Comment manipuler l opinion en démocratie"},
	{"auteur": "Jankiel Wiernik", "titre":"Un an à Treblinka"},
	{"auteur": "Georges Orwell", "titre":"Dans la dèche à Paris et à Londres"},
	{"auteur": "Ken Kesey", "titre":"La machine à brouillard"},
	{"auteur": "Eldridge Cleaver", "titre":"Un noir à l ombre"},
	{"auteur": "Razhig Keucheyan", "titre":"Les besoins artificiels"},
	{"auteur": "Gérard Mauger", "titre":"Repères pour résister à l idéologie dominante"},
	{"auteur": "John Steinbeck", "titre":"A l est d Eden"},
	{"auteur": "Italo Calvino", "titre":"Le sentier des nids d araignées"},
]